services:
  static-collection:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python manage.py collectstatic --no-input --clear
    working_dir: /app
    container_name: django-collectstatic
    env_file: .env
    volumes:
      - ./django_project:/app
      - static_volume:/app/staticfiles/

  web-server:
    command: gunicorn --bind 0.0.0.0:2680 --workers 25 django_project.wsgi
    expose:
      - 2680
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
      static-collection:
        condition: service_completed_successfully

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      web-server:
        condition: service_started
    volumes:
      - static_volume:/app/staticfiles/:ro
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest-arm64
    command: tunnel run
    container_name: cloudflared
    env_file:
      - .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped

volumes:
  static_volume: