services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/etc/data

  db-migration:
    build:
      context: django_project
      dockerfile: Dockerfile
    command: python django_project/manage.py migrate
    working_dir: /var/migrations
    container_name: django-migrations
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../personal-website:/var/migrations/

  web-server:
    build:
      context: django_project
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:2680 --workers 25 django_project.wsgi
    working_dir: /app/personal-website/django_project
    container_name: django-server
    ports:
      - "2680:2680"
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
      static-collection:
        condition: service_completed_successfully
    volumes:
      - ../personal-website:/app/personal-website/

  static-collection:
    build:
      context: django_project
      dockerfile: Dockerfile
    command: python django_project/manage.py collectstatic --no-input
    working_dir: /var/static
    container_name: django-collectstatic
    env_file: .env
    volumes:
      - ../personal-website:/var/static/

volumes:
  postgres_data:
    driver: local