services:
  db-migration:
    build:
      context: django_project
      dockerfile: Dockerfile
    command: python manage.py migrate
    working_dir: /app
    container_name: django-migrations
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./django_project:/app

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/etc/data
    restart: always

  web-server:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:2680
    working_dir: /app
    container_name: django-server
    ports:
      - "2680:2680"
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy
      db-migration:
        condition: service_completed_successfully
    volumes:
      - ./django_project:/app
    restart: always

volumes:
  postgres_data:
    driver: local